"""Generate a 4-bit greyscale anti-aliased font atlas for the OLED UI.

Rasterises printable ASCII (0x20..0x7E) from a TTF at a target pixel size using
supersampling for clean anti-aliasing, then emits a C header with per-glyph
4-bit coverage bitmaps + metrics. Mirrors the packing of generate_note_sprites.py
(4-bit, high nibble first).

Usage:
    pip install pillow
    python generate_font.py
"""

import os
from PIL import Image, ImageDraw, ImageFont

FONT_PATH   = os.path.join(os.path.dirname(__file__), "Inter-Regular.ttf")
OUT_PATH    = os.path.join(os.path.dirname(__file__),
                           "..", "firmware", "Core", "UI", "inter_font.h")

TARGET_PX   = 16          # on-screen text size (cell height ~ ascent+descent)
SS          = 4           # supersample factor for AA
FIRST, LAST = 0x20, 0x7E  # printable ASCII range


def pack_4bit(pixels):
    """Pack 4-bit values into bytes, high nibble first (pads odd length)."""
    if len(pixels) % 2:
        pixels = pixels + [0]
    return [(pixels[i] << 4) | pixels[i + 1] for i in range(0, len(pixels), 2)]


def render_glyph(font_hi, ascent_hi, descent_hi, ch):
    """Render one glyph supersampled, downsample, return metrics + 4-bit pixels.

    Returns (advance, w, h, left, top, pixels[]) where left/top are offsets from
    the pen origin and the text top-line (ascender), in final px.
    """
    pad_hi = 8 * SS
    adv_hi = font_hi.getlength(ch)
    W = int(adv_hi) + 2 * pad_hi
    H = ascent_hi + descent_hi + 2 * pad_hi

    img = Image.new("L", (W, H), 0)
    draw = ImageDraw.Draw(img)
    # anchor "la" = horizontal-left, vertical-ascender: text top at y=pad_hi.
    draw.text((pad_hi, pad_hi), ch, fill=255, font=font_hi, anchor="la")

    lo = img.resize((W // SS, H // SS), Image.LANCZOS)
    lo_w, lo_h = lo.size
    pen_x = pad_hi // SS      # pen origin (x) in final px
    top_ref = pad_hi // SS    # ascender top-line (y) in final px
    advance = int(round(adv_hi / SS))

    # Quantise to 4-bit FIRST, then bbox on coverage > 0 — this drops the faint
    # LANCZOS ringing halo (raw values below ~8/255 round to level 0) so the
    # glyph box is tight to the real ink instead of the resampling fringe.
    px = list(lo.getdata())
    q = [min(15, max(0, int(round(p * 15 / 255.0)))) for p in px]

    x0, y0, x1, y1 = lo_w, lo_h, -1, -1
    for y in range(lo_h):
        row = y * lo_w
        for x in range(lo_w):
            if q[row + x] > 0:
                if x < x0: x0 = x
                if x > x1: x1 = x
                if y < y0: y0 = y
                if y > y1: y1 = y

    if x1 < x0:                                  # empty glyph (e.g. space)
        return (advance, 0, 0, 0, 0, [])

    w = x1 - x0 + 1
    h = y1 - y0 + 1
    left = x0 - pen_x
    top = y0 - top_ref
    pixels = []
    for y in range(y0, y1 + 1):
        row = y * lo_w
        for x in range(x0, x1 + 1):
            pixels.append(q[row + x])
    return (advance, w, h, left, top, pixels)


def main():
    font_hi = ImageFont.truetype(FONT_PATH, TARGET_PX * SS)
    ascent_hi, descent_hi = font_hi.getmetrics()
    line_h = int(round((ascent_hi + descent_hi) / SS))
    ascent = int(round(ascent_hi / SS))

    glyphs = []
    total = 0
    for code in range(FIRST, LAST + 1):
        g = render_glyph(font_hi, ascent_hi, descent_hi, chr(code))
        glyphs.append((code, g))
        total += (g[1] * g[2] + 1) // 2

    lines = []
    lines.append("#ifndef INTER_FONT_H")
    lines.append("#define INTER_FONT_H")
    lines.append("")
    lines.append("/* Generated by graphical-ui-generator/generate_font.py — do not edit. */")
    lines.append(f"/* Inter Regular, {TARGET_PX}px, 4-bit AA coverage. */")
    lines.append("")
    lines.append("#include <stdint.h>")
    lines.append("")
    lines.append("typedef struct {")
    lines.append("    uint8_t advance, w, h;")
    lines.append("    int8_t  left, top;        /* offsets from pen origin / text top-line */")
    lines.append("    const uint8_t *pixels;    /* 4-bit packed, high nibble first; 0 if blank */")
    lines.append("} Glyph;")
    lines.append("")
    lines.append(f"#define FONT_FIRST   0x{FIRST:02X}")
    lines.append(f"#define FONT_LAST    0x{LAST:02X}")
    lines.append(f"#define FONT_LINE_H  {line_h}")
    lines.append(f"#define FONT_ASCENT  {ascent}")
    lines.append("")

    for code, (adv, w, h, left, top, pixels) in glyphs:
        if not pixels:
            continue
        packed = pack_4bit(pixels)
        lines.append(f"static const uint8_t g_{code:02X}[{len(packed)}] = {{")
        for i in range(0, len(packed), 16):
            row = ", ".join(f"0x{b:02X}" for b in packed[i:i + 16])
            lines.append(f"    {row},")
        lines.append("};")
    lines.append("")

    lines.append(f"static const Glyph inter_glyphs[FONT_LAST - FONT_FIRST + 1] = {{")
    for code, (adv, w, h, left, top, pixels) in glyphs:
        arr = f"g_{code:02X}" if pixels else "0"
        ch = chr(code)
        disp = ch if ch != '\\' else "backslash"
        lines.append(f"    {{ {adv}, {w}, {h}, {left}, {top}, {arr} }},  /* 0x{code:02X} {disp} */")
    lines.append("};")
    lines.append("")
    lines.append("#endif")
    lines.append("")

    with open(OUT_PATH, "w") as f:
        f.write("\n".join(lines))

    print(f"Font: {FONT_PATH}  size={TARGET_PX}px (SS={SS})")
    print(f"line_h={line_h} ascent={ascent}")
    print(f"glyphs={len(glyphs)} ({FIRST:#x}..{LAST:#x})  pixel bytes={total}")
    print(f"Wrote {os.path.normpath(OUT_PATH)}")


if __name__ == "__main__":
    main()
